// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel RandomLegalMoves
#pragma kernel SwapBackToOld
#pragma kernel ReWriteOldNumMoves
#pragma kernel GeneticSwap
#pragma kernel EvaluationSum


uint wang_hash(uint seed)
{
	seed = (seed ^ 61) ^ (seed >> 16);
	seed *= 9;
	seed = seed ^ (seed >> 4);
	seed *= 0x27d4eb2d;
	seed = seed ^ (seed >> 15);
	return seed;
}

float Random(uint seed) {
	return ((float)wang_hash(seed) / pow(10, 9)) / 4.5f;
}

int RandomRange(uint seed, int min, int max) {
	int dif = max - min;
	return ((int)floor(Random(seed) * dif)) + min;
}

struct Pos {
	int x;
	int y;
	int numMoves;
	int oldNumMoves;
	int depthBFS;
	int debugVal;
	int flagged;
};

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<Pos> testIntsA;
RWStructuredBuffer<Pos> testIntsB;
RWStructuredBuffer<Pos> testIntsC;
RWStructuredBuffer<float> sumsGreaterDivide;
RWStructuredBuffer<float> sumsLesserDivide;

uniform uint gridSize;
uniform float seedTime;

uniform uint divide;
uniform uint divideSide;
uniform uint greaterDivide;

uint seed = 0;
uint tempNumMoves;

[numthreads(16,16,3)]
void RandomLegalMoves(uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
	int chooseX = 0;

	float maxX = (id.x <= gridSize / 2) ? gridSize - id.x : gridSize - id.x / 2;
	float maxY = (id.y <= gridSize / 2) ? gridSize - id.y : gridSize - id.y / 2;

	int pos = id.x * gridSize + id.y;
	
	uint firstSeed = wang_hash(((id.x + gridSize) * gridSize + id.y * gridSize * 30) * seedTime * 10 * (id.z + gridSize));
	seed = wang_hash(firstSeed) * 2;

	int randomX = RandomRange(seed, 1, maxX);
	seed = wang_hash(seed) * 2;
	int randomY = RandomRange(seed, 1, maxY);
	seed = wang_hash(seed) * 2;

	float chooseRand = Random(seed);
	seed = wang_hash(seed) * 2;

	if (chooseRand < 0.5f) {
		chooseX = 1;
	}

	if (id.z == 2) {
		testIntsC[pos].x = id.x;
		testIntsC[pos].y = id.y;
		
		if (chooseX == 1) {
			testIntsC[pos].numMoves = (int)randomX;
			//testIntsC[pos].oldNumMoves = (int)randomX;
		}
		else {
			testIntsC[pos].numMoves = (int)randomY;
			//testIntsC[pos].oldNumMoves = (int)randomY;
		}
	}
	else if(id.z == 1) {
		testIntsB[pos].x = id.x;
		testIntsB[pos].y = id.y;

		if (chooseX == 1) {
			testIntsB[pos].numMoves = (int)randomX;
			//testIntsB[pos].oldNumMoves = (int)randomX;
		}
		else {
			testIntsB[pos].numMoves = (int)randomY;
			//testIntsB[pos].oldNumMoves = (int)randomY;
		}
	}
	else if (id.z == 0) {
		testIntsA[pos].x = id.x;
		testIntsA[pos].y = id.y;

		if (chooseX == 1) {
			testIntsA[pos].numMoves = (int)randomX;
			//testIntsA[pos].oldNumMoves = (int)randomX;
		}
		else {
			testIntsA[pos].numMoves = (int)randomY;
			//testIntsA[pos].oldNumMoves = (int)randomY;
		}
	}
}

[numthreads(16, 16, 3)]
void SwapBackToOld(uint3 id: SV_DispatchThreadID) {
	int pos = id.x * gridSize + id.y;
	if (id.z == 2) {
		testIntsC[pos].numMoves = testIntsC[pos].oldNumMoves;
	}
	else if (id.z == 1) {
		testIntsB[pos].numMoves = testIntsB[pos].oldNumMoves;
	}
	else if (id.z == 0) {
		testIntsA[pos].numMoves = testIntsA[pos].oldNumMoves;
	}
}

[numthreads(16, 16, 3)]
void ReWriteOldNumMoves(uint3 id: SV_DispatchThreadID) {
	int pos = id.x * gridSize + id.y;
	if (id.z == 2) {
		testIntsC[pos].oldNumMoves = testIntsC[pos].numMoves;
	}
	else if (id.z == 1) {
		testIntsB[pos].oldNumMoves = testIntsB[pos].numMoves;
	}
	else if (id.z == 0) {
		testIntsA[pos].oldNumMoves = testIntsA[pos].numMoves;
	}
}


[numthreads(4, 4, 3)]
void GeneticSwap(uint3 id: SV_DispatchThreadID) {

}

[numthreads(4, 4, 3)]
void EvaluationSum(uint3 id: SV_DispatchThreadID) {

	int pos = id.x * gridSize + id.y;

	if (divideSide == 0) {
		if (id.y >= gridSize / divide) {
			if (id.z == 0) {
				//int greaterDivide = pow(((divide - 1) * gridSize )/ divide), 2);
				sumsGreaterDivide[0] += (float)testIntsA[pos].numMoves / greaterDivide;
			}
			else if (id.z == 1) {
				sumsGreaterDivide[1] += (float)testIntsB[pos].numMoves / greaterDivide;
			}
			else if (id.z == 2) {
				sumsGreaterDivide[2] += (float)testIntsC[pos].numMoves / greaterDivide;
			}
		}
	}
	else {
		if (id.x <= greaterDivide) {
			if (id.z == 0) {
				//int greaterDivide = pow(((divide - 1) * gridSize )/ divide), 2);
				sumsGreaterDivide[0] += (float)testIntsA[pos].numMoves / greaterDivide;
			}
			else if (id.z == 1) {
				sumsGreaterDivide[1] += (float)testIntsB[pos].numMoves / greaterDivide;
			}
			else if (id.z == 2) {
				sumsGreaterDivide[2] += (float)testIntsC[pos].numMoves / greaterDivide;
			}
		}
	}
}
